"""The cheapest rig this stack supports: one webcam on a mast, watching the arm.

This profile exists to keep an honest claim honest. The pitch is "an arm and a camera
on the head is enough to approach and grasp" — and the only way that stays true is if
the *least* capable configuration is exercised on every commit. So:

    SO-101            mock              head_mono
    ----------------  ----------------  --------------------------------
    stereo (OAK-D)    stereo            MONO — no depth of any kind
    eye_in_hand       fixed, overhead   fixed, on a mast, tilted 40 deg
    pitch_hold IK     pose IK           pose IK
    real URDF         no URDF           no URDF

The mono column is the interesting one. With no depth map, exactly one localization
strategy remains: intersect the pixel's sightline with the table plane
(:class:`perception.locate.PlaneRayLocalizer`). That is not a fallback — for an object
resting on a known surface it is often the *better* estimator, because a plane fitted
over thousands of pixels is a far stronger prior than a stereo match on one textureless
object. What mono genuinely costs you is objects that are not on the table.

The camera looks along +X and 40 degrees down from a mast 30 cm behind the base and
50 cm up, which is where a person would actually clamp a webcam to watch a desk robot.
Deliberately not overhead: an overhead camera makes the ray-to-plane intersection
nearly degenerate-free and would flatter the geometry. A tilted view has real
foreshortening, so a sign error in the extrinsics shows up as a metres-scale miss
rather than a wash.
"""

from __future__ import annotations

import numpy as np

from rax.robots.profiles import ArmProfile, CameraProfile, GripperProfile

#: EE pose components, in the order CartesianKinematics expects.
JOINT_NAMES = ("x", "y", "z", "rx", "ry", "rz")

LIMITS = (
    np.array([-1.0, -1.0, -1.0, -180.0, -180.0, -180.0]),
    np.array([+1.0, +1.0, +1.0, +180.0, +180.0, +180.0]),
)

#: Mast camera: 30 cm behind the base, 50 cm up, optical axis 40 deg below horizontal
#: and pointing along +X. As "x,y,z,rx,ry,rz" with the rotation as a rotation vector.
#: Generated by the construction documented in the module docstring — camera +Z is the
#: view direction, +Y is image-down, in the OpenCV optical convention.
HEAD_TF = "-0.300000,0.000000,0.500000,-1.702124,1.702124,-0.793714"

#: A 640x480 webcam with a 62 deg horizontal FOV, which is what a Logitech C270/C920
#: reports. Real numbers rather than the library's sentinel default, so the profile
#: describes a camera someone actually owns.
WEBCAM_INTRINSICS = (531.0, 531.0, 320.0, 240.0)

PROFILE = ArmProfile(
    name="head_mono",
    urdf="",                       # CartesianKinematics needs no robot model
    ee_frame="ee",
    joint_names=JOINT_NAMES,
    port="",

    ik="pose",
    pan_joint=None,
    pitch_chain=(),
    roll_joint=None,
    ik_seeds=(),

    home_deg=(0.18, 0.0, 0.16, 0.0, 0.0, 0.0),
    view_deg=(0.18, 0.0, 0.22, 0.0, 0.0, 0.0),
    survey_tilt_deg=None,

    joint_rate_max_dps=25.0,
    table_z_m=0.0,
    reach_min_m=0.05,
    reach_max_m=0.60,

    gripper=GripperProfile(
        open_pct=95.0,
        closed_pct=2.0,
        place_open_pct=60.0,
        # No current sensing on a hobby gripper; the grasp closes open-loop and the
        # contact threshold is never consulted. Left at the default rather than zero,
        # which would read as "contact on any current at all".
        contact_current_delta=8.0,
        tip_offset_m=0.0,
        hand_uv=None,              # a fixed camera has no constant fingertip pixel
    ),
    camera=CameraProfile(
        kind="mono",               # the branch neither other profile takes
        mount="fixed",
        extrinsics=HEAD_TF,
        calibration_file=None,
        width=640,
        height=480,
        fps=30,
        use_depth=False,
        intrinsics_fallback=WEBCAM_INTRINSICS,
    ),
    bus=None,

    limits_deg=LIMITS,
)
